# Generated by Django 3.1.1 on 2020-09-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200908_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/project_imgs/%Y/%m/%d'),
        ),
    ]
